# Generated by Django 5.0.4 on 2024-04-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='board',
            field=models.CharField(choices=[('General', 'General'), ('Academic', 'Academic'), ('Entertainment', 'Entertainment'), ('Sports', 'Sports'), ('Politics', 'Politics'), ('Religion', 'Religion'), ('Technology', 'Technology'), ('Health', 'Health'), ('Fashion', 'Fashion'), ('Business', 'Business'), ('Science', 'Science'), ('Agriculture', 'Agriculture')], default='General', max_length=255),
        ),
    ]
